//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        public Subscription()
        {
            this.SubscriptionItems = new HashSet<SubscriptionItem>();
        }
    
        public int SubscriptionId { get; set; }
        public int AccountId { get; set; }
        public int ItemRetentionInDays { get; set; }
        public System.DateTime StartDateUtc { get; set; }
        public Nullable<System.DateTime> EndDateUtc { get; set; }
        public string Name { get; set; }
        public string ResourceUri { get; set; }
        public string Summary { get; set; }
        public string ContentType { get; set; }
        public System.DateTime LastRefreshedUtc { get; set; }
    
        public virtual ICollection<SubscriptionItem> SubscriptionItems { get; set; }
    }
}
