// <auto-generated />
namespace FeedReader.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class MovingMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MovingMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201508132123324_MovingMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
