// <auto-generated />
namespace FeedReader.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class SelectedIDs2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SelectedIDs2));
        
        string IMigrationMetadata.Id
        {
            get { return "201508150626421_SelectedIDs2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
